services:
  - type: web
    name: mealy-backend
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
  - type: static_site
    name: mealy-frontend
    env: node
    region: oregon
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: "https://mealy-backend.onrender.com"
